name: Push to branch Develop
on:
  repository_dispatch:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "Installing dependencies"
        run: npm ci
      - name: "Running test"
        env:
          NODE_ENV: development
          PORT: 3000
          TEST_PORT: 6666
        run: npm test

  
