name: Push to branch Develop
on:
  repository_dispatch:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "Installing dependencies"
        run: npm ci
      - name: "Running test"
        run: npm test
      - name: "Delete env dev config"
        run: git rm --cached '.env.development'
      - name: "Delete env prod config"
        run: git rm --cached '.env.production'
      - run: git commit -m 'delete env'
      - run: git push
        

  
