name: Push to branch Develop
on:
  repository_dispatch:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "Installing dependencies"
        run: npm install
  test-app:
    needs: install-dependencies
    runs-on: ubuntu-latest
    environment: development
    steps:
      - shell: bash
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          TEST_PORT: ${{ secrets.TEST_PORT }}
        run: npm run test
  
